// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.0
// source: Pozo/apiPozo/apiPozo.proto

package apiPozo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JugadaJugador struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdJugador int32   `protobuf:"varint,1,opt,name=IdJugador,proto3" json:"IdJugador,omitempty"`
	Jugada    []int32 `protobuf:"varint,2,rep,packed,name=Jugada,proto3" json:"Jugada,omitempty"`
	Etapa     int32   `protobuf:"varint,3,opt,name=Etapa,proto3" json:"Etapa,omitempty"`
}

func (x *JugadaJugador) Reset() {
	*x = JugadaJugador{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Pozo_apiPozo_apiPozo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadaJugador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadaJugador) ProtoMessage() {}

func (x *JugadaJugador) ProtoReflect() protoreflect.Message {
	mi := &file_Pozo_apiPozo_apiPozo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadaJugador.ProtoReflect.Descriptor instead.
func (*JugadaJugador) Descriptor() ([]byte, []int) {
	return file_Pozo_apiPozo_apiPozo_proto_rawDescGZIP(), []int{0}
}

func (x *JugadaJugador) GetIdJugador() int32 {
	if x != nil {
		return x.IdJugador
	}
	return 0
}

func (x *JugadaJugador) GetJugada() []int32 {
	if x != nil {
		return x.Jugada
	}
	return nil
}

func (x *JugadaJugador) GetEtapa() int32 {
	if x != nil {
		return x.Etapa
	}
	return 0
}

type Signal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sign bool `protobuf:"varint,1,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *Signal) Reset() {
	*x = Signal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Pozo_apiPozo_apiPozo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_Pozo_apiPozo_apiPozo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_Pozo_apiPozo_apiPozo_proto_rawDescGZIP(), []int{1}
}

func (x *Signal) GetSign() bool {
	if x != nil {
		return x.Sign
	}
	return false
}

type JugadorYEtapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdJugador int32 `protobuf:"varint,1,opt,name=IdJugador,proto3" json:"IdJugador,omitempty"`
	NroEtapa  int32 `protobuf:"varint,2,opt,name=NroEtapa,proto3" json:"NroEtapa,omitempty"`
}

func (x *JugadorYEtapa) Reset() {
	*x = JugadorYEtapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Pozo_apiPozo_apiPozo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadorYEtapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadorYEtapa) ProtoMessage() {}

func (x *JugadorYEtapa) ProtoReflect() protoreflect.Message {
	mi := &file_Pozo_apiPozo_apiPozo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadorYEtapa.ProtoReflect.Descriptor instead.
func (*JugadorYEtapa) Descriptor() ([]byte, []int) {
	return file_Pozo_apiPozo_apiPozo_proto_rawDescGZIP(), []int{2}
}

func (x *JugadorYEtapa) GetIdJugador() int32 {
	if x != nil {
		return x.IdJugador
	}
	return 0
}

func (x *JugadorYEtapa) GetNroEtapa() int32 {
	if x != nil {
		return x.NroEtapa
	}
	return 0
}

type JugadasArchivo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JugadasJugador string `protobuf:"bytes,1,opt,name=JugadasJugador,proto3" json:"JugadasJugador,omitempty"`
}

func (x *JugadasArchivo) Reset() {
	*x = JugadasArchivo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Pozo_apiPozo_apiPozo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadasArchivo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadasArchivo) ProtoMessage() {}

func (x *JugadasArchivo) ProtoReflect() protoreflect.Message {
	mi := &file_Pozo_apiPozo_apiPozo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadasArchivo.ProtoReflect.Descriptor instead.
func (*JugadasArchivo) Descriptor() ([]byte, []int) {
	return file_Pozo_apiPozo_apiPozo_proto_rawDescGZIP(), []int{3}
}

func (x *JugadasArchivo) GetJugadasJugador() string {
	if x != nil {
		return x.JugadasJugador
	}
	return ""
}

type MontoJugador struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Monto int32 `protobuf:"varint,1,opt,name=Monto,proto3" json:"Monto,omitempty"`
}

func (x *MontoJugador) Reset() {
	*x = MontoJugador{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Pozo_apiPozo_apiPozo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MontoJugador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MontoJugador) ProtoMessage() {}

func (x *MontoJugador) ProtoReflect() protoreflect.Message {
	mi := &file_Pozo_apiPozo_apiPozo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MontoJugador.ProtoReflect.Descriptor instead.
func (*MontoJugador) Descriptor() ([]byte, []int) {
	return file_Pozo_apiPozo_apiPozo_proto_rawDescGZIP(), []int{4}
}

func (x *MontoJugador) GetMonto() int32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

var File_Pozo_apiPozo_apiPozo_proto protoreflect.FileDescriptor

var file_Pozo_apiPozo_apiPozo_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x50, 0x6f, 0x7a, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x50, 0x6f, 0x7a, 0x6f, 0x2f, 0x61,
	0x70, 0x69, 0x50, 0x6f, 0x7a, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x70,
	0x69, 0x50, 0x6f, 0x7a, 0x6f, 0x22, 0x5b, 0x0a, 0x0d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x64, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x49, 0x64, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x74, 0x61, 0x70, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x74, 0x61,
	0x70, 0x61, 0x22, 0x1c, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x69, 0x67, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e,
	0x22, 0x49, 0x0a, 0x0d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x59, 0x45, 0x74, 0x61, 0x70,
	0x61, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x64, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x49, 0x64, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x4e, 0x72, 0x6f, 0x45, 0x74, 0x61, 0x70, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x4e, 0x72, 0x6f, 0x45, 0x74, 0x61, 0x70, 0x61, 0x22, 0x38, 0x0a, 0x0e, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x6f, 0x12, 0x26, 0x0a,
	0x0e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75,
	0x67, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x0c, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x4a, 0x75,
	0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x32, 0xc4, 0x01, 0x0a, 0x0c,
	0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x3b, 0x0a, 0x0e,
	0x45, 0x73, 0x63, 0x72, 0x69, 0x62, 0x69, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x16,
	0x2e, 0x61, 0x70, 0x69, 0x50, 0x6f, 0x7a, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x50, 0x6f, 0x7a, 0x6f,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0f, 0x52, 0x65, 0x74,
	0x6f, 0x72, 0x6e, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x16, 0x2e, 0x61,
	0x70, 0x69, 0x50, 0x6f, 0x7a, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x59, 0x45,
	0x74, 0x61, 0x70, 0x61, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x50, 0x6f, 0x7a, 0x6f, 0x2e, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x6f, 0x22, 0x00, 0x12,
	0x31, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x50, 0x6f,
	0x7a, 0x6f, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x50,
	0x6f, 0x7a, 0x6f, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72,
	0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x61, 0x70, 0x69, 0x50, 0x6f, 0x7a, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Pozo_apiPozo_apiPozo_proto_rawDescOnce sync.Once
	file_Pozo_apiPozo_apiPozo_proto_rawDescData = file_Pozo_apiPozo_apiPozo_proto_rawDesc
)

func file_Pozo_apiPozo_apiPozo_proto_rawDescGZIP() []byte {
	file_Pozo_apiPozo_apiPozo_proto_rawDescOnce.Do(func() {
		file_Pozo_apiPozo_apiPozo_proto_rawDescData = protoimpl.X.CompressGZIP(file_Pozo_apiPozo_apiPozo_proto_rawDescData)
	})
	return file_Pozo_apiPozo_apiPozo_proto_rawDescData
}

var file_Pozo_apiPozo_apiPozo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Pozo_apiPozo_apiPozo_proto_goTypes = []interface{}{
	(*JugadaJugador)(nil),  // 0: apiPozo.JugadaJugador
	(*Signal)(nil),         // 1: apiPozo.Signal
	(*JugadorYEtapa)(nil),  // 2: apiPozo.JugadorYEtapa
	(*JugadasArchivo)(nil), // 3: apiPozo.JugadasArchivo
	(*MontoJugador)(nil),   // 4: apiPozo.MontoJugador
}
var file_Pozo_apiPozo_apiPozo_proto_depIdxs = []int32{
	0, // 0: apiPozo.DataNodePozo.EscribirJugada:input_type -> apiPozo.JugadaJugador
	2, // 1: apiPozo.DataNodePozo.RetornarJugadas:input_type -> apiPozo.JugadorYEtapa
	1, // 2: apiPozo.DataNodePozo.Monto:input_type -> apiPozo.Signal
	1, // 3: apiPozo.DataNodePozo.EscribirJugada:output_type -> apiPozo.Signal
	3, // 4: apiPozo.DataNodePozo.RetornarJugadas:output_type -> apiPozo.JugadasArchivo
	4, // 5: apiPozo.DataNodePozo.Monto:output_type -> apiPozo.MontoJugador
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Pozo_apiPozo_apiPozo_proto_init() }
func file_Pozo_apiPozo_apiPozo_proto_init() {
	if File_Pozo_apiPozo_apiPozo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Pozo_apiPozo_apiPozo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadaJugador); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Pozo_apiPozo_apiPozo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Pozo_apiPozo_apiPozo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadorYEtapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Pozo_apiPozo_apiPozo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadasArchivo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Pozo_apiPozo_apiPozo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MontoJugador); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Pozo_apiPozo_apiPozo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Pozo_apiPozo_apiPozo_proto_goTypes,
		DependencyIndexes: file_Pozo_apiPozo_apiPozo_proto_depIdxs,
		MessageInfos:      file_Pozo_apiPozo_apiPozo_proto_msgTypes,
	}.Build()
	File_Pozo_apiPozo_apiPozo_proto = out.File
	file_Pozo_apiPozo_apiPozo_proto_rawDesc = nil
	file_Pozo_apiPozo_apiPozo_proto_goTypes = nil
	file_Pozo_apiPozo_apiPozo_proto_depIdxs = nil
}
