// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package apiJugador

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataNodeJugadorClient is the client API for DataNodeJugador service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataNodeJugadorClient interface {
	EscribirJugada(ctx context.Context, in *JugadaJugador, opts ...grpc.CallOption) (*Signal, error)
}

type dataNodeJugadorClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNodeJugadorClient(cc grpc.ClientConnInterface) DataNodeJugadorClient {
	return &dataNodeJugadorClient{cc}
}

func (c *dataNodeJugadorClient) EscribirJugada(ctx context.Context, in *JugadaJugador, opts ...grpc.CallOption) (*Signal, error) {
	out := new(Signal)
	err := c.cc.Invoke(ctx, "/apiJugador.DataNodeJugador/EscribirJugada", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataNodeJugadorServer is the server API for DataNodeJugador service.
// All implementations must embed UnimplementedDataNodeJugadorServer
// for forward compatibility
type DataNodeJugadorServer interface {
	EscribirJugada(context.Context, *JugadaJugador) (*Signal, error)
	mustEmbedUnimplementedDataNodeJugadorServer()
}

// UnimplementedDataNodeJugadorServer must be embedded to have forward compatible implementations.
type UnimplementedDataNodeJugadorServer struct {
}

func (UnimplementedDataNodeJugadorServer) EscribirJugada(context.Context, *JugadaJugador) (*Signal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EscribirJugada not implemented")
}
func (UnimplementedDataNodeJugadorServer) mustEmbedUnimplementedDataNodeJugadorServer() {}

// UnsafeDataNodeJugadorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataNodeJugadorServer will
// result in compilation errors.
type UnsafeDataNodeJugadorServer interface {
	mustEmbedUnimplementedDataNodeJugadorServer()
}

func RegisterDataNodeJugadorServer(s grpc.ServiceRegistrar, srv DataNodeJugadorServer) {
	s.RegisterService(&DataNodeJugador_ServiceDesc, srv)
}

func _DataNodeJugador_EscribirJugada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JugadaJugador)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeJugadorServer).EscribirJugada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiJugador.DataNodeJugador/EscribirJugada",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeJugadorServer).EscribirJugada(ctx, req.(*JugadaJugador))
	}
	return interceptor(ctx, in, info, handler)
}

// DataNodeJugador_ServiceDesc is the grpc.ServiceDesc for DataNodeJugador service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataNodeJugador_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apiJugador.DataNodeJugador",
	HandlerType: (*DataNodeJugadorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EscribirJugada",
			Handler:    _DataNodeJugador_EscribirJugada_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Jugador/apiJugador/apiJugador.proto",
}
