// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: Jugador/apiJugador/apiJugador.proto

package apiJugador

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JugadaJugador struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdJugador int32 `protobuf:"varint,1,opt,name=IdJugador,proto3" json:"IdJugador,omitempty"`
	Jugada    int32 `protobuf:"varint,2,opt,name=Jugada,proto3" json:"Jugada,omitempty"`
	Etapa     int32 `protobuf:"varint,3,opt,name=Etapa,proto3" json:"Etapa,omitempty"`
}

func (x *JugadaJugador) Reset() {
	*x = JugadaJugador{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Jugador_apiJugador_apiJugador_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadaJugador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadaJugador) ProtoMessage() {}

func (x *JugadaJugador) ProtoReflect() protoreflect.Message {
	mi := &file_Jugador_apiJugador_apiJugador_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadaJugador.ProtoReflect.Descriptor instead.
func (*JugadaJugador) Descriptor() ([]byte, []int) {
	return file_Jugador_apiJugador_apiJugador_proto_rawDescGZIP(), []int{0}
}

func (x *JugadaJugador) GetIdJugador() int32 {
	if x != nil {
		return x.IdJugador
	}
	return 0
}

func (x *JugadaJugador) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

func (x *JugadaJugador) GetEtapa() int32 {
	if x != nil {
		return x.Etapa
	}
	return 0
}

type Signal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sign bool `protobuf:"varint,1,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *Signal) Reset() {
	*x = Signal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Jugador_apiJugador_apiJugador_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_Jugador_apiJugador_apiJugador_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_Jugador_apiJugador_apiJugador_proto_rawDescGZIP(), []int{1}
}

func (x *Signal) GetSign() bool {
	if x != nil {
		return x.Sign
	}
	return false
}

var File_Jugador_apiJugador_apiJugador_proto protoreflect.FileDescriptor

var file_Jugador_apiJugador_apiJugador_proto_rawDesc = []byte{
	0x0a, 0x23, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f,
	0x72, 0x22, 0x5b, 0x0a, 0x0d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x64, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x49, 0x64, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x74, 0x61, 0x70,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x74, 0x61, 0x70, 0x61, 0x22, 0x1c,
	0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x32, 0x54, 0x0a, 0x0f,
	0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12,
	0x41, 0x0a, 0x0e, 0x45, 0x73, 0x63, 0x72, 0x69, 0x62, 0x69, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x61, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x2e, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x61, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x1a, 0x12, 0x2e, 0x61,
	0x70, 0x69, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x61, 0x70, 0x69, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Jugador_apiJugador_apiJugador_proto_rawDescOnce sync.Once
	file_Jugador_apiJugador_apiJugador_proto_rawDescData = file_Jugador_apiJugador_apiJugador_proto_rawDesc
)

func file_Jugador_apiJugador_apiJugador_proto_rawDescGZIP() []byte {
	file_Jugador_apiJugador_apiJugador_proto_rawDescOnce.Do(func() {
		file_Jugador_apiJugador_apiJugador_proto_rawDescData = protoimpl.X.CompressGZIP(file_Jugador_apiJugador_apiJugador_proto_rawDescData)
	})
	return file_Jugador_apiJugador_apiJugador_proto_rawDescData
}

var file_Jugador_apiJugador_apiJugador_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Jugador_apiJugador_apiJugador_proto_goTypes = []interface{}{
	(*JugadaJugador)(nil), // 0: apiJugador.JugadaJugador
	(*Signal)(nil),        // 1: apiJugador.Signal
}
var file_Jugador_apiJugador_apiJugador_proto_depIdxs = []int32{
	0, // 0: apiJugador.DataNodeJugador.EscribirJugada:input_type -> apiJugador.JugadaJugador
	1, // 1: apiJugador.DataNodeJugador.EscribirJugada:output_type -> apiJugador.Signal
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Jugador_apiJugador_apiJugador_proto_init() }
func file_Jugador_apiJugador_apiJugador_proto_init() {
	if File_Jugador_apiJugador_apiJugador_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Jugador_apiJugador_apiJugador_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadaJugador); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Jugador_apiJugador_apiJugador_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Jugador_apiJugador_apiJugador_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Jugador_apiJugador_apiJugador_proto_goTypes,
		DependencyIndexes: file_Jugador_apiJugador_apiJugador_proto_depIdxs,
		MessageInfos:      file_Jugador_apiJugador_apiJugador_proto_msgTypes,
	}.Build()
	File_Jugador_apiJugador_apiJugador_proto = out.File
	file_Jugador_apiJugador_apiJugador_proto_rawDesc = nil
	file_Jugador_apiJugador_apiJugador_proto_goTypes = nil
	file_Jugador_apiJugador_apiJugador_proto_depIdxs = nil
}
